name: CI

on:
  push:
    branches:
      - dev
    tags:
      - '*.*.*'

jobs:
  ci:
    name: Run CI
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Tests
        run: make test

      - name: Prepare
        id: prepare
        run: |
          echo ::set-output name=commit::${GITHUB_SHA}
          echo ::set-output name=build_num::${GITHUB_RUN_NUMBER}

          if [[ $GITHUB_REF_TYPE == 'branch' ]];
          then
            echo ::set-output name=version::dev
          else
            echo ::set-output name=version::${GITHUB_REF#refs/tags/}
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Publish lightscale geth
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: lightscale/geth:${{ steps.prepare.outputs.version }},lightscale/geth:latest
          build-args: |
            COMMIT=${{ steps.prepare.outputs.commit }}
            VERSION=${{ steps.prepare.outputs.version }}
            BUILDNUM=${{ steps.prepare.outputs.build_num }}
