name: CI

on:
  push:
    branches:
      - dev
    tags:
      - '*.*.*'

jobs:
  ci:
    name: Run CI
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - run: go mod download
      
      - name: Tests
        run: make test

      - name: Prepare
        id: prepare
        run: |
          if [[ $GITHUB_REF_TYPE == 'branch' ]];
          then
            echo "version=dev-$(echo $GITHUB_SHA | cut -c1-12)" >> $GITHUB_OUTPUT
          else
            echo "version=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Publish Kroma geth
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: kromanetwork/geth:${{ steps.prepare.outputs.version }},kromanetwork/geth:latest
          platforms: linux/arm64,linux/amd64
          build-args: |
            COMMIT=${{ github.sha }}
            VERSION=${{ steps.prepare.outputs.version }}
            BUILDNUM=${{ github.run_number }}
